/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_windowajouter_ghassen (void);
GtkWidget* create_windowafficher_ghassen (void);
GtkWidget* create_windowmeilleurmenu_ghassen (void);
